import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getCarrierByDot, getInspectionsByDot, getCrashesByDot, getInsuranceByDot } from "@/lib/socrata";
import { getCarrierBasics, getCarrierProfile, extractCarrierRecord } from "@/lib/fmcsa";
import { computeQuickRiskIndicator } from "@/lib/risk-score";

type Props = { params: { dotNumber: string } };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const dot = params.dotNumber;
  if (!/^\d{1,10}$/.test(dot)) return { title: "Report Not Found | FleetSight" };
  const carrier = await getCarrierByDot(parseInt(dot, 10));
  if (!carrier) return { title: "Report Not Found | FleetSight" };
  return {
    title: `Carrier Report: ${carrier.legal_name} — DOT ${dot} | FleetSight`,
    description: `Compliance and safety report for ${carrier.legal_name} (USDOT ${dot}). Generated by FleetSight.`,
  };
}

export default async function PublicReportPage({ params }: Props) {
  if (!/^\d{1,10}$/.test(params.dotNumber)) notFound();
  const dotNumber = parseInt(params.dotNumber, 10);

  const [carrier, inspections, crashes, insurance] = await Promise.all([
    getCarrierByDot(dotNumber),
    getInspectionsByDot(dotNumber, 100).catch(() => []),
    getCrashesByDot(dotNumber, 50).catch(() => []),
    getInsuranceByDot(dotNumber, 20).catch(() => []),
  ]);

  if (!carrier) notFound();

  let basics: unknown = null;
  let safetyRating: string | null = null;
  let allowedToOperate: string | null = null;
  try {
    const [basicsData, profile] = await Promise.all([
      getCarrierBasics(String(dotNumber)).catch(() => null),
      getCarrierProfile(String(dotNumber)).catch(() => null),
    ]);
    basics = basicsData;
    const record = extractCarrierRecord(profile);
    if (record) {
      const r = record.safetyRating ?? record.safety_rating;
      if (r && typeof r === "string" && r !== "None") safetyRating = r;
      if (typeof record.allowedToOperate === "string") allowedToOperate = record.allowedToOperate;
    }
  } catch {}

  const risk = computeQuickRiskIndicator({
    powerUnits: carrier.power_units ? parseInt(carrier.power_units, 10) : undefined,
    totalDrivers: carrier.total_drivers ? parseInt(carrier.total_drivers, 10) : undefined,
    addDate: carrier.add_date,
    mcs150Date: carrier.mcs150_date,
    statusCode: carrier.status_code,
  });

  const totalViols = inspections.reduce((s, i) => s + (parseInt(i.viol_total ?? "0", 10) || 0), 0);
  const totalOos = inspections.reduce((s, i) => s + (parseInt(i.oos_total ?? "0", 10) || 0), 0);
  const oosRate = inspections.length > 0 ? ((totalOos / inspections.length) * 100).toFixed(1) : "N/A";
  const totalFatalities = crashes.reduce((s, c) => s + (parseInt(c.fatalities ?? "0", 10) || 0), 0);
  const totalInjuries = crashes.reduce((s, c) => s + (parseInt(c.injuries ?? "0", 10) || 0), 0);

  type BasicEntry = { desc: string; pct: number };
  let basicScores: BasicEntry[] = [];
  if (basics && typeof basics === "object") {
    const obj = basics as Record<string, unknown>;
    const content = obj.content ?? obj;
    const measures = (content as Record<string, unknown>)?.basics ?? (content as Record<string, unknown>)?.basicsArray;
    if (Array.isArray(measures)) {
      basicScores = measures.map((m: Record<string, unknown>) => ({
        desc: String(m.basicsDescription ?? m.basics_description ?? ""),
        pct: Number(m.basicsPercentile ?? m.basics_percentile ?? 0),
      }));
    }
  }

  const statusOk = carrier.status_code === "A" || allowedToOperate === "Y";
  const now = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

  return (
    <main className="min-h-screen bg-white text-[#1a1917] print:bg-white">
      {/* Print-friendly report */}
      <div className="mx-auto max-w-3xl px-6 py-8">
        {/* Report header */}
        <div className="flex items-start justify-between border-b-2 border-[#d97757] pb-4 mb-6">
          <div>
            <p className="text-xs font-semibold uppercase tracking-widest text-[#d97757]">Carrier Compliance Report</p>
            <h1 className="mt-1 text-2xl font-bold">{carrier.legal_name}</h1>
            {carrier.dba_name && <p className="text-sm text-gray-500">DBA {carrier.dba_name}</p>}
          </div>
          <div className="text-right">
            <p className="text-xs text-gray-400">Generated {now}</p>
            <p className="text-xs text-gray-400">by FleetSight</p>
            {risk && (
              <div className={`mt-2 inline-block rounded-lg px-3 py-1 text-center ${
                risk.grade === "A" || risk.grade === "B" ? "bg-emerald-50 text-emerald-700" :
                risk.grade === "C" ? "bg-amber-50 text-amber-700" :
                "bg-rose-50 text-rose-700"
              }`}>
                <span className="text-lg font-bold">{risk.grade}</span>
                <span className="ml-1 text-[10px]">Risk</span>
              </div>
            )}
          </div>
        </div>

        {/* Carrier details */}
        <section className="mb-6">
          <h2 className="text-sm font-bold uppercase tracking-wider text-gray-500 mb-3">Carrier Information</h2>
          <div className="grid grid-cols-2 gap-x-8 gap-y-2 text-sm">
            <div><span className="text-gray-500">USDOT:</span> <span className="font-medium">{dotNumber}</span></div>
            <div><span className="text-gray-500">MC Number:</span> <span className="font-medium">{carrier.docket1 ? `MC-${carrier.docket1}` : "N/A"}</span></div>
            <div><span className="text-gray-500">Status:</span> <span className={`font-medium ${statusOk ? "text-emerald-700" : "text-rose-700"}`}>{statusOk ? "Active / Authorized" : "Inactive / Not Authorized"}</span></div>
            <div><span className="text-gray-500">Safety Rating:</span> <span className="font-medium">{safetyRating ?? "Not Rated"}</span></div>
            <div><span className="text-gray-500">Address:</span> <span className="font-medium">{carrier.phy_city}, {carrier.phy_state} {carrier.phy_zip}</span></div>
            <div><span className="text-gray-500">Phone:</span> <span className="font-medium">{carrier.phone ?? "N/A"}</span></div>
            <div><span className="text-gray-500">Power Units:</span> <span className="font-medium">{carrier.power_units ?? "N/A"}</span></div>
            <div><span className="text-gray-500">Drivers:</span> <span className="font-medium">{carrier.total_drivers ?? "N/A"}</span></div>
            <div><span className="text-gray-500">Authority Date:</span> <span className="font-medium">{carrier.add_date ? new Date(carrier.add_date).toLocaleDateString() : "N/A"}</span></div>
            <div><span className="text-gray-500">Hazmat:</span> <span className="font-medium">{carrier.hm_ind === "Y" ? "Yes" : "No"}</span></div>
          </div>
        </section>

        {/* Safety stats */}
        <section className="mb-6">
          <h2 className="text-sm font-bold uppercase tracking-wider text-gray-500 mb-3">Safety Summary</h2>
          <div className="grid grid-cols-3 gap-4 sm:grid-cols-6">
            {[
              { label: "Inspections", value: inspections.length },
              { label: "Violations", value: totalViols },
              { label: "OOS", value: totalOos },
              { label: "OOS Rate", value: `${oosRate}%` },
              { label: "Crashes", value: crashes.length },
              { label: "Fatalities", value: totalFatalities, warn: totalFatalities > 0 },
            ].map((s) => (
              <div key={s.label} className="rounded-lg border border-gray-200 px-3 py-2 text-center">
                <p className={`text-lg font-bold ${s.warn ? "text-rose-600" : ""}`}>{s.value}</p>
                <p className="text-[10px] text-gray-400">{s.label}</p>
              </div>
            ))}
          </div>
        </section>

        {/* BASIC Scores */}
        {basicScores.length > 0 && (
          <section className="mb-6">
            <h2 className="text-sm font-bold uppercase tracking-wider text-gray-500 mb-3">BASIC Scores</h2>
            <div className="space-y-2">
              {basicScores.map((b) => (
                <div key={b.desc} className="flex items-center gap-3">
                  <span className="w-44 text-xs text-gray-600 truncate">{b.desc}</span>
                  <div className="flex-1 h-3 rounded-full bg-gray-100 overflow-hidden">
                    <div
                      className={`h-full rounded-full ${b.pct >= 75 ? "bg-rose-500" : b.pct >= 50 ? "bg-amber-400" : "bg-emerald-400"}`}
                      style={{ width: `${b.pct}%` }}
                    />
                  </div>
                  <span className={`w-10 text-right text-xs font-medium ${b.pct >= 75 ? "text-rose-600" : ""}`}>{b.pct}%</span>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Insurance */}
        {insurance.length > 0 && (
          <section className="mb-6">
            <h2 className="text-sm font-bold uppercase tracking-wider text-gray-500 mb-3">Insurance ({insurance.length} records)</h2>
            <table className="w-full text-xs">
              <thead>
                <tr className="border-b border-gray-200 text-left text-gray-500">
                  <th className="pb-1">Type</th>
                  <th className="pb-1">Insurer</th>
                  <th className="pb-1 text-right">Coverage</th>
                  <th className="pb-1 text-right">Effective</th>
                </tr>
              </thead>
              <tbody>
                {insurance.slice(0, 10).map((ins, i) => (
                  <tr key={i} className="border-b border-gray-100">
                    <td className="py-1">{ins.mod_col_1 ?? "N/A"}</td>
                    <td className="py-1 text-gray-600">{ins.name_company ?? "N/A"}</td>
                    <td className="py-1 text-right">{ins.underl_lim_amount ? `$${parseInt(ins.underl_lim_amount).toLocaleString()}` : "N/A"}</td>
                    <td className="py-1 text-right text-gray-500">{ins.effective_date ? new Date(ins.effective_date).toLocaleDateString() : "N/A"}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </section>
        )}

        {/* Footer / CTA */}
        <div className="mt-8 border-t border-gray-200 pt-4 text-center print:hidden">
          <p className="text-sm text-gray-500 mb-3">
            This report shows a summary. For chameleon detection, background checks, VIN tracking, and more:
          </p>
          <Link
            href={`/carrier/${dotNumber}`}
            className="inline-block rounded-lg bg-[#d97757] px-5 py-2 text-sm font-medium text-white hover:bg-[#c4623f] transition-colors"
          >
            View Full Intelligence on FleetSight
          </Link>
        </div>

        <div className="mt-6 text-center text-[10px] text-gray-400">
          <p>Data sourced from FMCSA, DOT, and NHTSA. Generated by FleetSight on {now}.</p>
          <p className="mt-1">
            <Link href="/" className="text-[#d97757] hover:underline">fleetsight.vercel.app</Link>
          </p>
        </div>
      </div>
    </main>
  );
}
